version: "3.5"
services:
  app:
    build: .
    volumes:
      - ./public:/app/public
      - ./res:/app/res
      - ./src:/app/src
      - ./views:/app/views
    environment:
      REDIS_URL: redis://redis:6379/0
    links:
      - redis
    env_file:
      - ./development.env
  redis:
    image: redis:3.2-alpine
