version: "2"
services:
  app:
    build: .
    volumes:
      - ./:/app
    environment:
      REDIS_URL: redis://redis:6379/0
    links:
      - redis
    env_file:
      - ./development.env
  redis:
    extends:
      image: redis:3.2-alpine
