name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        version: 8.9.4

    - uses: actions/cache@v1
      name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Yarn
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: yarn install

    - name: Build and Lint
      run: yarn typecheck
